global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'blackbox'
    metrics_path: /probe
    file_sd_configs:
      - files:
          - '/home/rboris/IdeaProjects/Blackbox_exporter'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [ module ]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115


